version: "3.3"

services:
  database:
    container_name: pokedjango_database
    image: postgres
    restart: always
    volumes:
      - ./.pgdata:/var/lib/postgresql/data
    environment:
      - LC_ALL=C.UTF-8
      - POSTGRES_PASSWORD=pokedjango
      - POSTGRES_USER=pokedjango
      - POSTGRES_DB=pokemondjango
    ports:
      - 5432:5432