# Generated by Django 4.0.3 on 2022-03-19 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='elementos',
            new_name='elemento',
        ),
    ]
