# Generated by Django 4.0.3 on 2022-03-24 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipo', '0003_elemento_delete_elementos'),
        ('pokemon', '0002_rename_elementos_pokemon_elemento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='elemento',
            field=models.ManyToManyField(to='tipo.elemento'),
        ),
    ]
