# Generated by Django 4.0.3 on 2022-03-23 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0002_rename_elementos_pokemon_elemento'),
        ('tipo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tipo',
            new_name='Elementos',
        ),
    ]
