# Generated by Django 4.0.3 on 2022-03-24 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0002_rename_elementos_pokemon_elemento'),
        ('tipo', '0002_rename_tipo_elementos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Elemento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Elementos',
        ),
    ]
