name: PokéDjango!

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    env:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: django
        ports: [ '5432:5432' ]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Copiar Configurações .env
        run: |
          cp contrib/env-sample .env

      - name: Flake8
        uses: py-actions/flake8@v1
        with:
          checkName: 'flake8_py3'

      - name: Test with pytest
        run: |
           run pytest